# Generated by Django 4.0.4 on 2022-05-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
